#!/usr/bin/env python3

import argparse
import certrip

parser = argparse.ArgumentParser()
parser.add_argument("host", type=str)
parser.add_argument("-p", "--port", type=int, default=443)

args = parser.parse_args()

host = args.host
port = args.port

hosts = certrip.certrip(host, port)
for host in hosts:
    print(host)
