#!/usr/bin/env python3

import sys
import argparse
import certrip
import io

parser = argparse.ArgumentParser()
parser.add_argument("host", type=str, nargs='?', default=sys.stdin)
parser.add_argument("-p", "--port", type=int, default=443)

args = parser.parse_args()
port = args.port

host = args.host
if(isinstance(host, io.IOBase)):
    host = host.read()

hosts = certrip.certrip(host, port)
for host in hosts:
    print(host)
